(load (merge-pathnames "std/fftw-ffi.lisp" *spectral-root*))

(defun ensure-vector (x)
  "Coerce list to vector; return other sequences (e.g. arrays) unchanged."
  (if (listp x) (coerce x 'vector) x))

(defun ensure-double-float-vector (x)
  "Ensure input is a double-float vector. Coerces lists and non-float arrays."
  (convert-to-float (ensure-vector x)))

(defun convert-to-float (input)
  "Convert the input 1D array to a float array. Do nothing if the array is already double float."
  (when (and (arrayp input) (= (array-rank input) 1)
	     (eq (array-element-type input) 'double-float))
    (return-from convert-to-float input))
  (let ((float-array (make-array (length input) :element-type 'double-float)))
    (dotimes (i (length input))
      (setf (aref float-array i) (coerce (aref input i) 'double-float)))
    float-array))

(defun fft-fn (input)
  "Fast Fourier Transform of the input signal."
  (fftw-ffi:fft-forward (convert-to-float input)))

(defun cfft-fn (input)
  "Complex forward Fast Fourier Transform of the input signal"
  (fftw-ffi:fft-forward input))

(defun fft-inverse (input)
  "Inverse Fast Fourier Transform of the input signal."
  (fftw-ffi:fft-backward (convert-to-float input)))

(defun find-peaks-fn (data)
  "Return 1D array of indices of local maxima. Strict: x[i] > both neighbors."
  (let* ((vec (ensure-vector data))
	 (n (length vec))
	 (peaks '()))
    (when (zerop n)
      (return-from find-peaks-fn (vector)))
    (when (= n 1)
      (return-from find-peaks-fn (vector 0)))
    ;; i=0: peak if greater than right neighbor
    (when (> (elt vec 0) (elt vec 1))
      (push 0 peaks))
    ;; interior: peak if greater than both neighbors
    (loop for i from 1 to (- n 2) do
      (when (and (> (elt vec i) (elt vec (1- i)))
		 (> (elt vec i) (elt vec (1+ i))))
	(push i peaks)))
    ;; i=n-1: peak if greater than left neighbor
    (when (> (elt vec (1- n)) (elt vec (- n 2)))
      (push (1- n) peaks))
    (coerce (nreverse peaks) 'vector)))

(defun bandpass-fn (params signal)
  "Bandpass filter: keep frequencies in [f_low, f_high] Hz. Params = [f_low f_high sample_rate]."
  (let* ((params-vec (ensure-vector params))
	 (f-low (coerce (elt params-vec 0) 'double-float))
	 (f-high (coerce (elt params-vec 1) 'double-float))
	 (fs (coerce (elt params-vec 2) 'double-float))
	 (data (ensure-double-float-vector signal))
	 (n (length data))
	 (spec (fftw-ffi:fft-forward (map 'vector (lambda (x) (complex x 0.0d0)) data))))
    (unless (>= n 2)
      (spectral-error "bandpass: signal must have at least 2 samples, got ~A" n))
    ;; Zero bins outside [f_low, f_high]. Bin k has freq k*Fs/N (k<=N/2) or (N-k)*Fs/N (k>N/2)
    (dotimes (k n)
      (let ((freq (if (<= k (floor n 2))
		      (* k fs (/ n))
		      (* (- n k) fs (/ n)))))
	(unless (and (>= freq f-low) (<= freq f-high))
	  (setf (aref spec k) (complex 0.0d0 0.0d0)))))
    (let ((filtered (fftw-ffi:fft-backward spec)))
      (map 'vector #'realpart filtered))))

(defun smooth-fn (window-size signal)
  "Boxcar moving average. window_size points, same-length output, partial windows at edges."
  (let* ((vec (ensure-vector signal))
	 (n (length vec))
	 (w (max 1 (floor (coerce window-size 'real)))))
    (when (zerop n)
      (return-from smooth-fn (vector)))
    (let ((half (floor w 2))
	  (result (make-array n :element-type 'double-float)))
      (dotimes (i n)
	(let ((lo (max 0 (- i half)))
	      (hi (min (1- n) (+ i half))))
	  (setf (aref result i)
		(/ (loop for j from lo to hi sum (coerce (elt vec j) 'double-float))
		   (1+ (- hi lo))))))
      result)))

;; Savitzky-Golay: compute convolution kernel from (window_length, poly_order)
(defun savgol-kernel (m n)
  "Return 1D array of SG coefficients for window m, polynomial order n."
  (let* ((x-center (/ (1- m) 2.0d0))
	 (X (make-array (list m (1+ n)) :element-type 'double-float :initial-element 0.0d0)))
    (dotimes (i m)
      (let ((xi (- i x-center)))
	(setf (aref X i 0) 1.0d0)
	(loop for j from 1 to n do
	  (setf (aref X i j) (* (aref X i (1- j)) xi)))))
    ;; (X'X)^{-1} X' via Gauss-Jordan; we need first row of result
    (let* ((np1 (1+ n))
	   (XtX (make-array (list np1 np1) :element-type 'double-float :initial-element 0.0d0)))
      ;; XtX = X' * X
      (dotimes (i np1)
	(dotimes (j np1)
	  (setf (aref XtX i j)
		(loop for k from 0 below m sum (* (aref X k i) (aref X k j))))))
      ;; Augment with identity for Gauss-Jordan to get XtX^{-1}
      (let ((aug (make-array (list np1 (* 2 np1)) :element-type 'double-float)))
	(dotimes (i np1)
	  (dotimes (j np1)
	    (setf (aref aug i j) (aref XtX i j)))
	  (dotimes (j np1)
	    (setf (aref aug i (+ np1 j)) (if (= i j) 1.0d0 0.0d0))))
	;; Gauss-Jordan elimination
	(dotimes (pivot np1)
	  (let ((p (aref aug pivot pivot)))
	    (when (< (abs p) 1.0d-14)
	      (spectral-error "savgol: singular matrix for window ~A poly ~A" m n))
	    (dotimes (col (* 2 np1))
	      (setf (aref aug pivot col) (/ (aref aug pivot col) p)))
	    (dotimes (row np1)
	      (unless (= row pivot)
		(let ((f (aref aug row pivot)))
		  (dotimes (col (* 2 np1))
		    (decf (aref aug row col) (* f (aref aug pivot col)))))))))
	;; aug now has [I | XtX^{-1}]. Compute first row of XtX^{-1} * X' = kernel
	(let ((kernel (make-array m :element-type 'double-float)))
	  (dotimes (j m)
	    (setf (aref kernel j)
		  (loop for i from 0 below np1 sum (* (aref aug 0 (+ np1 i)) (aref X j i)))))
	  kernel)))))

(defun savgol-reflect (vec idx)
  (let ((n (length vec)))
    (when (= n 1) (return-from savgol-reflect (aref vec 0)))
    (let* ((period (* 2 (1- n)))
	   (idx (mod idx period)))
      (aref vec (if (>= idx n) (- period idx) idx)))))

(defun savgol-fn (params signal)
  "Savitzky-Golay polynomial smoothing. Params = [window_length poly_order]."
  (let* ((params-vec (ensure-vector params))
	 (m-raw (max 3 (floor (coerce (elt params-vec 0) 'real))))
	 (m (if (oddp m-raw) m-raw (1+ m-raw)))
	 (n (min (1- m) (max 0 (floor (coerce (elt params-vec 1) 'real)))))
	 (vec (ensure-vector signal))
	 (len (length vec)))
    (when (zerop len)
      (return-from savgol-fn (vector)))
    (let* ((kernel (savgol-kernel m n))
	   (half (floor m 2))
	   (result (make-array len :element-type 'double-float)))
      (dotimes (i len)
	(setf (aref result i)
	      (loop for k from 0 below m
		    sum (* (aref kernel k)
			   (coerce (savgol-reflect vec (+ i (- k half))) 'double-float)))))
      result)))

(defun lowpass-fn (params signal)
  "Lowpass filter: keep frequencies below f_cutoff Hz. Params = [f_cutoff sample_rate]."
  (let* ((params-vec (ensure-vector params))
	 (f-cutoff (coerce (elt params-vec 0) 'double-float))
	 (fs (coerce (elt params-vec 1) 'double-float))
	 (data (ensure-double-float-vector signal))
	 (n (length data))
	 (spec (fftw-ffi:fft-forward (map 'vector (lambda (x) (complex x 0.0d0)) data))))
    (unless (>= n 2)
      (spectral-error "lowpass: signal must have at least 2 samples, got ~A" n))
    (dotimes (k n)
      (let ((freq (if (<= k (floor n 2))
		      (* k fs (/ n))
		      (* (- n k) fs (/ n)))))
	(when (> freq f-cutoff)
	  (setf (aref spec k) (complex 0.0d0 0.0d0)))))
    (let ((filtered (fftw-ffi:fft-backward spec)))
      (map 'vector #'realpart filtered))))

(defun highpass-fn (params signal)
  "Highpass filter: keep frequencies above f_cutoff Hz. Params = [f_cutoff sample_rate]."
  (let* ((params-vec (ensure-vector params))
	 (f-cutoff (coerce (elt params-vec 0) 'double-float))
	 (fs (coerce (elt params-vec 1) 'double-float))
	 (data (ensure-double-float-vector signal))
	 (n (length data))
	 (spec (fftw-ffi:fft-forward (map 'vector (lambda (x) (complex x 0.0d0)) data))))
    (unless (>= n 2)
      (spectral-error "highpass: signal must have at least 2 samples, got ~A" n))
    (dotimes (k n)
      (let ((freq (if (<= k (floor n 2))
		      (* k fs (/ n))
		      (* (- n k) fs (/ n)))))
	(when (<= freq f-cutoff)
	  (setf (aref spec k) (complex 0.0d0 0.0d0)))))
    (let ((filtered (fftw-ffi:fft-backward spec)))
      (map 'vector #'realpart filtered))))

(defun bandstop-fn (params signal)
  "Bandstop (notch) filter: zero frequencies in [f_low, f_high] Hz. Params = [f_low f_high sample_rate]."
  (let* ((params-vec (ensure-vector params))
	 (f-low (coerce (elt params-vec 0) 'double-float))
	 (f-high (coerce (elt params-vec 1) 'double-float))
	 (fs (coerce (elt params-vec 2) 'double-float))
	 (data (ensure-double-float-vector signal))
	 (n (length data))
	 (spec (fftw-ffi:fft-forward (map 'vector (lambda (x) (complex x 0.0d0)) data))))
    (unless (>= n 2)
      (spectral-error "bandstop: signal must have at least 2 samples, got ~A" n))
    (dotimes (k n)
      (let ((freq (if (<= k (floor n 2))
		      (* k fs (/ n))
		      (* (- n k) fs (/ n)))))
	(when (and (>= freq f-low) (<= freq f-high))
	  (setf (aref spec k) (complex 0.0d0 0.0d0)))))
    (let ((filtered (fftw-ffi:fft-backward spec)))
      (map 'vector #'realpart filtered))))

(defun find-valleys-fn (data)
  "Return 1D array of indices of local minima. Strict: x[i] < both neighbors."
  (let* ((vec (ensure-vector data))
	 (n (length vec))
	 (valleys '()))
    (when (zerop n)
      (return-from find-valleys-fn (vector)))
    (when (= n 1)
      (return-from find-valleys-fn (vector 0)))
    (when (< (elt vec 0) (elt vec 1))
      (push 0 valleys))
    (loop for i from 1 to (- n 2) do
      (when (and (< (elt vec i) (elt vec (1- i)))
		 (< (elt vec i) (elt vec (1+ i))))
	(push i valleys)))
    (when (< (elt vec (1- n)) (elt vec (- n 2)))
      (push (1- n) valleys))
    (coerce (nreverse valleys) 'vector)))

(defun psd-fn (signal)
  "Power spectral density: |FFT(signal)|^2. Returns real array of power at each frequency bin."
  (let* ((vec (ensure-double-float-vector signal))
	 (n (length vec))
	 (spec (fftw-ffi:fft-forward (map 'vector (lambda (x) (complex x 0.0d0)) vec))))
    (map 'vector (lambda (c) (* (abs c) (abs c))) spec)))

(defun detrend-fn (signal)
  "Remove linear trend from signal. Same-length output."
  (let* ((vec (ensure-vector signal))
	 (n (length vec)))
    (when (zerop n)
      (return-from detrend-fn (vector)))
    (when (= n 1)
      (return-from detrend-fn (make-array 1 :element-type 'double-float
					 :initial-element (coerce (elt vec 0) 'double-float))))
    (let* ((x-sum 0.0d0) (y-sum 0.0d0) (xy-sum 0.0d0) (xx-sum 0.0d0))
      (dotimes (i n)
	(let ((xi (coerce i 'double-float))
	      (yi (coerce (elt vec i) 'double-float)))
	  (incf x-sum xi)
	  (incf y-sum yi)
	  (incf xy-sum (* xi yi))
	  (incf xx-sum (* xi xi))))
      (let* ((n-d (coerce n 'double-float))
	     (denom (- (* n-d xx-sum) (* x-sum x-sum)))
	     (slope (if (< (abs denom) 1.0d-20) 0.0d0
			(/ (- (* n-d xy-sum) (* x-sum y-sum)) denom)))
	     (intercept (/ (- y-sum (* slope x-sum)) n-d))
	     (result (make-array n :element-type 'double-float)))
	(dotimes (i n)
	  (setf (aref result i)
		(- (coerce (elt vec i) 'double-float)
		   (+ intercept (* slope (coerce i 'double-float))))))
	result))))

(defun differentiate-fn (signal)
  "First derivative via central differencing. Same-length output; edges use forward/backward diff."
  (let* ((vec (ensure-vector signal))
	 (n (length vec))
	 (result (make-array n :element-type 'double-float)))
    (when (zerop n)
      (return-from differentiate-fn (vector)))
    (when (= n 1)
      (return-from differentiate-fn (make-array 1 :element-type 'double-float :initial-element 0.0d0)))
    (when (= n 2)
      (setf (aref result 0) (- (coerce (elt vec 1) 'double-float) (coerce (elt vec 0) 'double-float))
	    (aref result 1) (aref result 0))
      (return-from differentiate-fn result))
    (setf (aref result 0)
	  (- (coerce (elt vec 1) 'double-float) (coerce (elt vec 0) 'double-float)))
    (loop for i from 1 to (- n 2) do
      (setf (aref result i)
	    (/ (- (coerce (elt vec (1+ i)) 'double-float)
		  (coerce (elt vec (1- i)) 'double-float))
	       2.0d0)))
    (setf (aref result (1- n))
	  (- (coerce (elt vec (1- n)) 'double-float)
	     (coerce (elt vec (- n 2)) 'double-float)))
    result))

(register-op 'fft #'fft-fn 1)
(register-op 'ifft #'fft-inverse 1)
(register-op 'cfft #'cfft-fn 1)
(register-op 'find-peaks #'find-peaks-fn 1)
(register-op 'find-valleys #'find-valleys-fn 1)
(register-op 'bandpass #'bandpass-fn 2)
(register-op 'lowpass #'lowpass-fn 2)
(register-op 'highpass #'highpass-fn 2)
(register-op 'bandstop #'bandstop-fn 2)
(register-op 'smooth #'smooth-fn 2)
(register-op 'savgol #'savgol-fn 2)
(register-op 'psd #'psd-fn 1)
(register-op 'detrend #'detrend-fn 1)
(register-op 'differentiate #'differentiate-fn 1)
